### ISSUE TITLE
how to hook the apns payload

### ISSUE THREAD

**Issue by jzp113** [eclair4151/Push-For-Apollo#1]
hi guys, did you know how to hook the apns payloads, like above the rc values
```
{
    "aps":{
        "alert":"哈哈哈1111234",
        "sound":"default",
        "badge":1
    },
    "rc":{
             "cType":"PR",
             "fId":"2121",
             "oName":"RC:TxtMsg",
             "tId":"3232",
             "id":"5FSClm2gQ9V9BZ-kUZn58B",
             "rc-dlt-identifier":"2FSClm2gQ9Q9BZ-kUZn54B"
     }
 
}
```

**Comment by eclair4151** [comment]
i have not hooked the apns payload myself so i dont know what it looks like, but you should be able to do this yourself by hooking into application delegate didlaunchwithoptions using theos or something siilar and inspect the payload.
